// Copyright 2026 Davide Faconti
// SPDX-License-Identifier: MIT
//
// gen_test_frame — a tiny NATIVE (host) build-time helper. It compresses a known
// plaintext with the project's native conan libzstd (1.5.7 — the exact encoder
// pin the Go server / CLI use) and emits a C++ header embedding BOTH the produced
// ZSTD frame bytes AND the original plaintext. The wasm smoke main then decodes
// that frame with the DECODER-ONLY zstddeclib amalgamation (also 1.5.7) and
// asserts the result is byte-for-byte the plaintext.
//
// This makes the wasm decode test FUNCTIONAL evidence, not a self-fulfilling
// round-trip: the frame is produced by a different (full, native) zstd build and
// decoded by the single-file wasm decoder. The frame layout (content-size in the
// header, one-shot frame) is exactly what the v1 server emits for
// BODY_ENCODING_ZSTD batch bodies (spec §6.4).
//
// Built and run on the HOST (never cross-compiled). Usage:
//   gen_test_frame <output_header_path>

#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <fstream>
#include <string>
#include <vector>

#include <zstd.h>

int main(int argc, char** argv) {
  if (argc != 2) {
    std::fprintf(stderr, "usage: %s <output_header_path>\n", argv[0]);
    return 2;
  }

  // A representative plaintext: stands in for a marshaled MessageBatchBody. Made
  // long + repetitive so the frame is genuinely compressed (output < input),
  // proving the decoder reinflates real compressed content rather than a stored
  // block.
  std::string plaintext;
  plaintext.reserve(4096);
  for (int i = 0; i < 256; ++i) {
    plaintext += "mcap-cloud wasm decode-core smoke: batch body chunk ";
    plaintext += std::to_string(i);
    plaintext += "\n";
  }

  const size_t bound = ZSTD_compressBound(plaintext.size());
  std::vector<char> frame(bound);
  // Level 3 (the libzstd default; the server uses the default level too). The
  // produced frame carries the content size in its header — the decoder relies
  // on ZSTD_getFrameContentSize, exactly as session_decode.cpp's zstdDecodeAll.
  const size_t n = ZSTD_compress(frame.data(), frame.size(), plaintext.data(), plaintext.size(), 3);
  if (ZSTD_isError(n)) {
    std::fprintf(stderr, "ZSTD_compress failed: %s\n", ZSTD_getErrorName(n));
    return 1;
  }
  frame.resize(n);

  std::ofstream out(argv[1], std::ios::binary | std::ios::trunc);
  if (!out) {
    std::fprintf(stderr, "cannot open output %s\n", argv[1]);
    return 1;
  }

  out << "// GENERATED by gen_test_frame.cpp at build time. Do not edit.\n";
  out << "// A real ZSTD frame (native conan libzstd 1.5.7 encoder, level 3) +\n";
  out << "// its plaintext, embedded for the wasm decode-core smoke.\n";
  out << "#pragma once\n";
  out << "#include <cstddef>\n#include <cstdint>\n\n";
  out << "namespace mcap_cloud_wasm_smoke {\n\n";

  auto emit_array = [&out](const char* name, const char* data, size_t len) {
    out << "inline constexpr unsigned char " << name << "[] = {";
    for (size_t i = 0; i < len; ++i) {
      if (i % 16 == 0) {
        out << "\n  ";
      }
      out << static_cast<unsigned>(static_cast<unsigned char>(data[i])) << ",";
    }
    out << "\n};\n";
    out << "inline constexpr std::size_t " << name << "_len = " << len << ";\n\n";
  };

  emit_array("kZstdFrame", frame.data(), frame.size());
  emit_array("kPlaintext", plaintext.data(), plaintext.size());

  out << "}  // namespace mcap_cloud_wasm_smoke\n";
  out.close();

  std::fprintf(stderr, "gen_test_frame: %zu-byte plaintext -> %zu-byte zstd frame -> %s\n", plaintext.size(),
               frame.size(), argv[1]);
  return 0;
}
